I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 993, in script
    show Anthony Sad at two_left
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 993, in script
    show Anthony Sad at two_left
  File "D:\Josh\ProgramFiles\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Josh\ProgramFiles\renpy-8.3.7-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "D:\Josh\ProgramFiles\renpy-8.3.7-sdk\renpy\exports\displayexports.py", line 489, in show
    img = i(img) # type: ignore
TypeError: 'tuple' object is not callable

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
Study Group 1.0
Thu Aug  7 13:39:44 2025
